import Head from 'next/head'
import { GetStaticProps, GetStaticPropsResult } from 'next'
import { createTheme, ThemeProvider, } from '@mui/material/styles'
import { ratherThemeOptions } from '../../ratherThemeOptions'
import NavbarAdmin from '../components/navbar/NavbarAdmin'
import RoomTable from '../components/table/room/RoomTable'

const theme = createTheme(ratherThemeOptions);

interface Props {
}

export default function Room() {
  return (
    <ThemeProvider theme={theme}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavbarAdmin />
      <main>
        <RoomTable />
      </main>
    </ThemeProvider >
  )
}

export const getStaticProps: GetStaticProps<Props> = async (): Promise<GetStaticPropsResult<Props>> => {
  return {
    props: {
    }
  };
}
