import Head from 'next/head'
import { GetStaticProps, GetStaticPropsResult } from 'next'
import Navbar from './components/navbar/Navbar'
import RoomsTable from './components/table/room/RoomsTable'
import StudentsTable from './components/table/student/StudentsTable'
import { createTheme, ThemeProvider, } from '@mui/material/styles'
import { ratherThemeOptions } from '../ratherThemeOptions'

const theme = createTheme(ratherThemeOptions);

interface Props {
}

export default function Admin() {
  return (
    <ThemeProvider theme={theme}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <RoomsTable />
        <StudentsTable />
      </main>
    </ThemeProvider >
  )
}

export const getStaticProps: GetStaticProps<Props> = async (): Promise<GetStaticPropsResult<Props>> => {
  // const rooms = await getRooms();
  return {
    props: {
    }
  };
}
