import Head from 'next/head'
import { Inter } from 'next/font/google'
import { GetStaticProps, GetStaticPropsResult } from 'next'
import Navbar from './components/Navbar'
import Link from 'next/link'
import RoomsTable from './RoomsTable'
import StudentsTable from './StudentsTable'
import axios from 'axios';
import { useEffect, useState } from 'react'
import { Room, Student } from '@/types'
const inter = Inter({ subsets: ['latin'] })

interface Props {
}

export default function Admin() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <RoomsTable />
        <StudentsTable />
      </main>
    </>
  )
}

export const getStaticProps: GetStaticProps<Props> = async (): Promise<GetStaticPropsResult<Props>> => {
  // const rooms = await getRooms();
  // console.log(rooms)

  return {
    props: {
    }
  };
}
