import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { GetStaticPropsResult } from 'next'
import { Room } from '@/types'
import { getRooms } from './api/hello'

const inter = Inter({ subsets: ['latin'] })

interface Props {
  rooms: Room[];
}

export default function Home({ rooms }: Props) {

  const overviewHandle = (reserve: string) => {
    router.push({
      pathname: '/overview',
      query: { reserve }
    });
  }
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.tsx</code>
          </p>
        </div>

        <div className={styles.grid}>
          {
            rooms.map((room) => {
              return (
                <div key={room.id}>
                  <h2 className={inter.className}>
                    {room.name}
                  </h2>
                  <p className={inter.className}>
                    {room.description}
                  </p>
                </div>
              )
            })
          }
        </div>

      </main>
    </>
  )
}

export async function getStaticProps(): Promise<GetStaticPropsResult<Props>> {
  const rooms = await getRooms();
  console.log(rooms)

  return {
    props: {
      rooms
    }
  };
}

