import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { GetStaticPropsResult } from 'next'
import { Room } from '@/types'
import { getRooms } from './api/hello'
import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })

interface Props {
  rooms: Room[];
}

export default function Home({ rooms }: Props) {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Rooms</h1>

        <div className={styles.grid}>
          {
            rooms.map((room) => {
              return (
                <div key={room.id}>
                  <Link href={{ pathname: "/room/[id]", query: { id: room.id, name: room.name, description: room.description } }}>
                    <h2 className={inter.className}>
                      {room.name}
                    </h2>
                    <p className={inter.className}>
                      {room.description}
                    </p>
                  </Link>
                </div>
              )
            })
          }
        </div>

      </main>
    </>
  )
}

export async function getStaticProps(): Promise<GetStaticPropsResult<Props>> {
  const rooms = await getRooms();
  console.log(rooms)

  return {
    props: {
      rooms
    }
  };
}

