import Head from 'next/head'
import { GetStaticProps, GetStaticPropsContext, GetStaticPropsResult } from 'next'
import { Relationship, Student } from '@/types'
import { useRouter } from 'next/router'
import PageTitle from '../components/PageTitle'
import Navbar from '../components/navbar/Navbar'
import { Container, Grid } from '@mui/material'
import BasicCard from '../components/BasicCard'
import { createTheme, ThemeProvider, } from '@mui/material/styles';
import { ratherThemeOptions } from '../../ratherThemeOptions';
import axios from 'axios'
import { API_STUDENTS_RELATIONSHIP, BASE } from '@/routes'
import { useEffect, useState } from 'react'

const theme = createTheme(ratherThemeOptions);

interface Props {
  relationships: Relationship[];
}

export default function StudentPage() {
  const router = useRouter();
  const [relationships, setRelationships] = useState<Relationship[]>([]);
  const { id, name, surname } = router.query as { id: string, name: string, surname: string };


  useEffect(() => {
    if (id !== undefined)
      getRelationships();
  }, [id]);

  const getRelationships = async () => {
    const studentsResponse = await axios.get(BASE + API_STUDENTS_RELATIONSHIP + id);
    setRelationships(studentsResponse.data);
  }


  return (
    <ThemeProvider theme={theme}>
      <Head>
        <title>Create Next App Student</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        {
          name && surname &&
          <PageTitle title={name} description={surname} />
        }
        <Container sx={{ py: 8 }} maxWidth="md">
          <Grid container spacing={4}>
            {
              relationships && relationships.map((relationshipItem) => {
                return (
                  <Grid item key={relationshipItem._id} xs={12} sm={6} md={4}>
                    <BasicCard
                      id={relationshipItem._id}
                      title={`${relationshipItem.student2.name}, ${relationshipItem.student2.surname}`}
                      description={relationshipItem.relationship}
                      textButton="" />
                  </Grid>
                )
              })
            }
          </Grid>
        </Container>
      </main>
    </ThemeProvider>
  )
}

export async function getStaticPaths() {
  return {
    paths: [],
    fallback: true,
  }
}

export const getStaticProps: GetStaticProps<Props> = async ({ params }: GetStaticPropsContext):
  Promise<GetStaticPropsResult<Props>> => {
  
  return {
    props: {
      relationships: []
    }
  };
}

